- pyproject.toml
Pythonの依存関係にpytorchとpynktrombonegymを追加しました。
poetry add を用いて以下のパッケージをインストールし、pyproject.tomlを編集しました。  
- torch1.13
- pynktrombonegym (from https://github.com/matsuo-group24-PinkTrombone/PynkTromboneGym)  
- pyproject.toml   
[tool.poetry.dependencies]
> Pythonの依存関係を追加

- AboutProject.md
- Dockerfile
- Makefile
- SetupProject.md
- scripts/docker-entrypoint.sh
- scripts/setup-on-aws.sh
#9 に従って、Dockerを用いた開発環境を整備しました。    
- Dockerfileおよび[Docker Imageを公開](https://hub.docker.com/repository/docker/gesonanko/speech-generation/general)
- Dockerイメージの作成のために`scripts/docker-entrypoint.sh`を作成
- AWSインスタンス上でセットアップするための`scripts/setup-on-aws.sh`を作成  
- MakefileにDockerのbuildおよびrunコマンドを追記  
- 環境の構築手順を`SetupProject.md`に記載  
- `AboutProject.md`の環境(依存関係)を修正  
- Makefile  
- AboutProject.md
> 環境構築の方法を整備しました。

- .pre-commit-config.yaml
pre-commitのshellcheckに無視するエラー項目を追記しました
- .pre-commit-config.yaml
- make format
> Add shellcheck ignore

- src/models/abc/_types.py
- src/models/abc/controller.py
- src/models/abc/observation_auto_encoder.py
- src/models/abc/prior.py
- src/models/abc/transition.py
- tests/models/abc/test_controller.py
- tests/models/abc/test_observation_auto_encoder.py
- tests/models/abc/test_prior.py
- tests/models/abc/test_transition.py
#18 に基づいて、5つの抽象クラスを実装しました。Controllerモデルといった具体的なモデルの実装はこれらのモデルを継承して行います。    
今回は具体的にパラメータを持つ抽象クラスのみを作成しました。次のプルリクエストで学習時に動作させるインターフェイス用抽象クラスを作成します。  
- `src/models/abc/`下に次の抽象クラスを 実装  
- Transition (trainsition.py)
- Prior (prior.py)
- ObservationEncoder (observation_auto_encoder.py)
- ObservationDecoder (observation_auto_encoder.py)
- Controller (controller.py)
- 型アノテーションのためのファイルを追加  
- src/models/abc/_types.py  
- 上記のクラスのテストコードを追加  
- `src/models/abc/`下のファイルすべて
- `tests/models/abc/`下のファイルすべて
@seichi042I @takeshun256 具体的にモデルを設計するときはこのクラスの抽象インターフェイスを必ず実装してください。メソッドやクラスのドキュメンテーションを参考にお願いします。わからないことがあれば issue #18 かDiscordに書き込んでください。
> コンポーネントモデルの抽象クラス作成

- .devcontainer/devcontainer.json
- Dockerfile
- Makefile
- SetupProject.md
- scripts/docker-entrypoint.sh
ローカル環境上でのDockerによる開発環境の方法を整備しました。  
セットアップ方法は 変更された`SetupProject.md`を参照ください。  
- VSCodeによる自動Docker環境セットアップのための`.devcontainer/devcontainer.json`を追加  
- Dockerイメージをビルド・起動し、VSCode上からアクセスする方法のドキュメントを追加  
- .devcontainer/devcontainer.json
- Dockerfile 
- Makefileの`docker-build`および`docker-run`コマンド  
- scripts/docker-entrypoint.sh
- SetupProject.md
VSCodeの自動Docker環境セットアップは非常に処理が重いので非推奨です。
> ローカル環境上でのDockerによる開発環境の方法を整備しました。  

- src/models/abc/controller.py
- tests/models/abc/test_controller.py
抽象Controllerモデルにabstract property `hidden_shape`を実装しました。
#18 
抽象Controllerモデルにabstract property `hidden_shape`を追加
- src/models/abc/controller.py
- tests/models/abc/test_controller.py
> 抽象Controllerモデルにabstract property `hidden_shape`を実装しました。

- configs/README.md
#17 のinstantiateに関するドキュメントを追加しました。具象クラスの設計に直接かかわる内容なのでここだけ早急に作りました。  
- configs/README.mdに hydra.utils.instantiateのドキュメントを追加  
- configs/README.md
> Hydraのinstantiateのドキュメントを追加  

- src/models/components/transition.py
- tests/models/components/test_transition.py
#37 TransitionModelの実装
- src/models/components/transition.py
- tests/models/components/test_transition.py
現時点では以下のみ
- src/models/components/transition.py
- tests/models/components/test_transition.py
__call__もオーバーライドしているのは、実装の際引数が参照できた方がいいと考えたからです。
> TransitionModelの実装

- src/env/make_env.py
- tests/env/test_make_env.py
#51 環境作成関数make_envの実装ブランチです。
- src/env/make_env.py
- tests/src/env/test_make_env.py
上記ファイル
> 環境作成関数make_envの実装

- pyproject.toml
- src/models/dreamer.py
- tests/models/test_dreamer.py
#57 
- Dreamerの内部でTensorboardに記録する処理を実装しました。
- pyproject.tomlに依存関係を追加しました
- Dreamerクラスに`log`メソッドを作成しました。
- dreamer.pyの機能とテストコード、またそれにかかわるテストコード全般
> Dreamerクラスにtensorboardによる記録処理を実装しました

- src/models/dreamer.py
Dreamerのcontroller_training_stepを修正しました
controller_hiddenをdoneで初期化する処理を追加
> Dreamerのcontroller_training_stepを修正しました

- src/models/dreamer.py
- tests/models/test_dreamer.py
#67 
- src/models/dreamer.py
- tests/models/test_dreamer.py
上記ファイルの他
- src/trainer.py の`Trainer`の動作に影響します
> Fix observation space

- src/models/abc/agent.py
- src/models/components/agent.py
- tests/models/abc/dummy_classes.py
- tests/models/components/test_agent.py
#54 
`explorer`メソッドを実装しました。[-1,1]の一様分布からサンプルしたノイズを`action_noise_ratio`のハイパラで混合して`action`を返します。 
いくつかテストを修正しました。
> Agentクラスを実装しました。

- src/trainer.py
- tests/test_trainer.py
#73 
trainer.fit()で学習中の様子がわかるようにログを出力する
- src/trainer.py
上記ファイル
> ログをコンソールにアウトプット

- src/models/components/observation_auto_encoder.py
- tests/models/components/test_observation_auto_encoder.py
> FIX decoder return value order

- configs/model/dreamer.yaml
- configs/train.yaml
- configs/trainer/trainer.yaml
- src/models/dreamer.py
- src/train.py
- src/trainer.py
- src/utils/reset_seed.py
#52 
train.pyを作成しました。それの実行に伴って発生したエラーを修正しました。  
- train.pyを更新
- reset_seed関数を追加
- dreamer.pyのエラーを修正
> train関数を実装し、学習を開始しました。

- src/models/components/linear_layers.py
- tests/models/components/test_linear_layers.py
#86 
Linear層の構造を簡単にへんこうできるようにするためのクラスの実装
- src/models/components/linear_layers.py
- tests/models/components/linear_layers.py
このファイルは現時点でどこにもimportされていないため影響はこのファイル内にとどまる
> linear_layersの実装とテスト

- configs/experiment/example.yaml
- configs/train.yaml
#82 
次のようにして実験用設定を実行します。  詳細は `configs/experiment/example.yaml`を参照してください。  
```sh
python src/train.py experiment=example
```
- configs/experiment/example.yamlを追加
- configs/train.yamlを更新
> 実験用のconfigファイルを作成し、上書きできる機能を追加しました。  

- src/models/abc/agent.py
演算デバイス管理のためにAgentクラスの`hidden`と`controller_hidden`属性をプロパティにし、それぞれ直接格納先のクラスの変数を参照するようにしました。  
agent.pyを変更。`hidden`と`controller_hidden` の属性をプロパティにした。`setter`も実装した。
> agentの`hidden`と`controller_hidden`をproperty化

- src/env/log_mel_spectrogram.py
- tests/env/test_log_mel_spectrogram.py
#97 
- `ObservationWrapper`クラス`LogMelSpectrogram`を作成
> LogMelSpectrogramに変換する観測ラッパークラスを作成しました。  
